name: jeodezi
description: >
  Jeodezi is Dart version of Jeodezi Kotlin which is based of Chris Veness's amazing work Geodesy Functions. Geodesy Functions is written in JavaScript and contains dozens of functions to make calculations about:
    Geodesic calculations (distances, bearings, etc) covering both spherical earth and ellipsoidal earth models, and both trigonometry-based and vector-based approaches.
    Ellipsoidal-earth coordinate systems covering both historical datums and modern terrestrial reference frames (TRFs).
version: 1.0.3
repository: https://github.com/bahadirarslan/jeodezi_dart

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
