name: jeodezi
description: jeodezi is Dart Geodesy Functions Library
version: 1.0.1
repository: https://github.com/bahadirarslan/jeodezi_dart

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
